.TH "SigmoidParameterMapper" 3 "Fri Mar 23 2018" "Version 1.0" "A Kalman Library (AKL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SigmoidParameterMapper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SigmoidParameterMapper\&.h>\fP
.PP
Inherits \fBAbstractParameterMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSigmoidParameterMapper\fP (double \fBmin\fP, double \fBmax\fP)"
.br
.ti -1c
.RI "vector< double > \fBmap\fP (vector< double > problemParameters)"
.br
.ti -1c
.RI "vector< double > \fBunmap\fP (vector< double > kalmanParameters)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBmin\fP"
.br
.ti -1c
.RI "double \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the \fBAbstractParameterMapper\fP class that map the problem parameters into the kalman parameters using a sigmoid function with a user preseted range\&. 
.PP
Definition at line 17 of file SigmoidParameterMapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SigmoidParameterMapper::SigmoidParameterMapper (double min, double max)"
Constructor that sets the range of mapping to (min,max) 
.PP
\fBParameters:\fP
.RS 4
\fImin\fP Minimum value in the problem parameters range\&. 
.br
\fImax\fP Maximum value in the problem parameters range\&. 
.RE
.PP

.PP
Definition at line 12 of file SigmoidParameterMapper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< double > SigmoidParameterMapper::map (vector< double > problemParameters)\fC [virtual]\fP"
Maps the problem parameters into the space of parameters where kalman filter optimize them\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproblemParameters\fP Set of problem parameters\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Set of kalman parameters 
.RE
.PP

.PP
Implements \fBAbstractParameterMapper\fP\&.
.PP
Definition at line 17 of file SigmoidParameterMapper\&.cpp\&.
.SS "vector< double > SigmoidParameterMapper::unmap (vector< double > kalmanParameters)\fC [virtual]\fP"
Maps the kalman parameters into the space of problem parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkalmanParameters\fP Set of kalman parameters\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Set of problem parameters\&. 
.RE
.PP

.PP
Implements \fBAbstractParameterMapper\fP\&.
.PP
Definition at line 26 of file SigmoidParameterMapper\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double SigmoidParameterMapper::max\fC [private]\fP"
Maximum value in the problem parameters range\&. 
.PP
Definition at line 21 of file SigmoidParameterMapper\&.h\&.
.SS "double SigmoidParameterMapper::min\fC [private]\fP"
Minimum value in the problem parameters range\&. 
.PP
Definition at line 19 of file SigmoidParameterMapper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for A Kalman Library (AKL) from the source code\&.
